#!/usr/bin/env bash
set -e

USER=team254
HOST=ec2.team254.com
APP=cheesy-parts
SCRIPT_NAME=parts_server

echo "Deploying $APP from Git master branch..."
echo
ssh $USER@$HOST "cd /opt/sites/$APP && git checkout -f && git pull && bundle install && bundle exec rake db:migrate && sudo -n /usr/bin/systemctl restart $APP.service"
echo
echo "Deployed $APP."
