#!/usr/bin/env bash
set -e

USER=team254
HOST=ec2.team254.com
APP=cheesy-parts
BRANCH=master

echo "Deploying $APP from Git $BRANCH branch..."
echo
ssh "$USER@$HOST" "cd /opt/sites/$APP && git fetch origin && git checkout -f $BRANCH && git reset --hard origin/$BRANCH && sudo -n /usr/bin/systemctl start $APP-prepare.service && sudo -n /usr/bin/systemctl restart $APP.service"
echo
echo "Deployed $APP."
